### PR TITLE
Django 1.9 support

### PR DESCRIPTION
**Pull request by thijstriemstra**
Fixes the `ImportError: No module named 'django.utils.importlib'` error with Django 1.9.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Only the py3.3 builder died with the following error:

```
ImportError: cannot import name find_spec
```
Is 3.3 even supported for Django 1.9?

**Comment by thijstriemstra** [comment]
Turns out it isn't:

```
Django 1.9 requires Python 2.7, 3.4, or 3.5. We highly recommend and only officially support the latest release of each series.

The Django 1.8 series is the last to support Python 3.2 and 3.3.
```

I'll get rid of the 3.3 build for Django 1.9 then...

**Comment by bak1an** [comment]
Looks good to me. 

Perhaps squash can be done, so there are 3 commits instead of 4. "add django 1.9 build" / "fix django 1.9 build" commit pair seems redundant.

**Comment by ashwoods** [comment]
Better too many commits as too few :) all tests pass here, so I'm ok.

**Comment by thijstriemstra** [comment]
Thanks! Could you also create a new release so the tests in my project pass again? ;)

**Comment by jezdez** [comment]
@thijstriemstra Feel free to do the release yourself, see the [contributing docs](https://github.com/jazzband/django-queued-storage/blob/master/CONTRIBUTING.md).

**Comment by thijstriemstra** [comment]
Hmm my intitial thought was you'll need my pypi username (don't you?) but this isn't mentioned in the docs you linked.

**Comment by thijstriemstra** [comment]
And I'd also like to bump the version..

**Comment by bak1an** [comment]
@thijstriemstra 
@jezdez 

Let me checkout how this works :shipit:

**Comment by bak1an** [comment]
@thijstriemstra Looks like it worked - https://pypi.python.org/pypi/django-queued-storage/0.8.0

**Comment by thijstriemstra** [comment]
Thanks!

**Comment by jezdez** [comment]
@thijstriemstra Sorry, I need to expand on what you can do in the contributing docs, but in general Jazzband projects are set up to allow members to do releases to PyPI by simply pushing a Git tag. No need for the PyPI username as Jazzband will use its own account for that.

**Pull request merged**
